# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: nwt-agent-pool

variables:
- group: staging-var

stages:
- stage: 'CI'
  jobs:
  - job: 'build'
    steps:

    - script: |
        sudo apt-get update
        sudo apt-get -y install zip
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'

    - task: Npm@1
      inputs:
        command: 'install'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/bootcamp-app.zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    # - task: PublishPipelineArtifact@1
    #   inputs:
    #     targetPath: '$(Pipeline.Workspace)'
    #     artifact: 'nwtCI$(Build.BuildId)'
    #     publishLocation: 'pipeline'

- stage: 'CD_S'
  jobs:
#   - job:
#     steps:
#     - task: DownloadBuildArtifacts@0
#       inputs:
#         buildType: 'current'
#         downloadType: 'single'
#         artifactName: 'drop'
#         downloadPath: '$(System.ArtifactsDirectory)'
  

  - deployment: staging
    environment: 'dev'
    variables:
      - group: staging-var
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              package: '$(System.ArtifactsDirectory)'
              
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '../**/*.zip'
              destinationFolder: 'bootcamp-app'
              cleanDestinationFolder: true
              overwriteExistingFiles: false
        
          - script:
              ansible-playbook /home/adminuser/myagent/_work/1/s/ansible/playbook.yml -i /home/adminuser/myagent/_work/1/s/ansible/inventory --extra-vars "group=Staging"
    
          # - task: CmdLine@2
          #   inputs:
          #     script: 
          #       sudo apt install ansible
          # - task: Ansible@0
          #   inputs:  
          #     ansibleInterface: 'agentMachine'
          #     playbookPathOnAgentMachine: '/home/adminuser/agent/myagent/_work/1/s/ansible/playbook.yml'
          #     inventoriesAgentMachine: 'file'
          #     inventoryFileOnAgentMachine: '/home/adminuser/agent/myagent/_work/1/s/ansible/inventory-staging'
          
# - stage: 'CD_P'
#   jobs:
#   - deployment: prod
#     environment: 'prod'
#     variables:
#       - group: prod-var
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: CmdLine@2
#             inputs:
#               package: '$(Pipline.Workspace)/**/*.zip'

#           - task: ExtractFiles@1
#             inputs:
#               archiveFilePatterns: '**/*.zip'
#               destinationFolder: 'bootcamp-app'
#               cleanDestinationFolder: true
#               overwriteExistingFiles: true
#           - task: CmdLine@2
#             inputs:
#               script: 'mv .env .env-prod'          
#           - script: |
#               ansible-playbook -i /home/adminuser/_work/1/s/ansible/inventory-staging /home/adminuser/_work/1/s/ansible/playbook.yml --extra-vars "group=prod"
    




      # - task: CmdLine@2
      #   inputs:
      #     script: npm install pm2 -g
      #     package: '$(pipline.workspace)/**/*.zip'


#- stage: 'CD'
#   jobs:
#   - job: 'staging'
#     steps:  
#     - task: DownloadBuildArtifacts@0
#       inputs:
#         buildType: 'current'
#         downloadType: 'single'
#         artifactName: 'nwtCI$(Build.BuildId)'
#         downloadPath: '$(System.ArtifactsDirectory)'
    
#     
